// <auto-generated />
using AsyncWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AsyncWeb.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20210407001053_addedSeededData")]
    partial class addedSeededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AsyncWeb.Models.Amenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MuchFun"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MuchDIO"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MuchMareofNight"
                        });
                });

            modelBuilder.Entity("AsyncWeb.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Mysterious Room",
                            Country = " Country of Mystery",
                            Name = " The uhhh room",
                            Phone = "123 345 7442",
                            State = "ScoobySnack",
                            StreetAddress = " 123 Mystery Street"
                        },
                        new
                        {
                            Id = 2,
                            City = "JOJOOO",
                            Country = " Girly teen girl",
                            Name = " Niceu Niceu Very Niceu",
                            Phone = "109 876 5432",
                            State = "Adventure of Bizarre",
                            StreetAddress = " 321 sesame street"
                        },
                        new
                        {
                            Id = 3,
                            City = "NightmareFun",
                            Country = "La La Land",
                            Name = "Chimkin of Nightmares",
                            Phone = "111 222 3334",
                            State = "fshh",
                            StreetAddress = "456 elm street"
                        });
                });

            modelBuilder.Entity("AsyncWeb.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Layout = 1,
                            Name = "Myst"
                        },
                        new
                        {
                            Id = 2,
                            Layout = 2,
                            Name = "JOJO"
                        },
                        new
                        {
                            Id = 3,
                            Layout = 0,
                            Name = "Night"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
